# scenario_name: "toy_scenario_001"
# output_dir: results
# scenario_name: "toy_GA"
# output_dir: results/GA
scenario_name: "toy_ADS"
output_dir: results/ADS


space:
  width: 100.0
  height: 100.0
  range: 40.0    # 通信可能距離

sim:
  max_steps: 500
  time_step: 1.0    # シミュレーションの時間ステップ

command_center:
  position: [50.0, 50.0]

repair_depot:
  position: [50.0, 50.0]
  repair_duration: 10   # 修理に要するステップ数

failure_model:
  module: acta.sim.failure_models
  class: WeibullFailureModel
  params:
    lam: 200   # 故障率 λ
    k: 1.5        # 形状パラメータ k

# task_selection:
#   module: acta.sim.task_selection
#   class: NearestIncompleteTaskSelector
#   params: {}

# task_selection:
#   module: acta.sim.task_selection
#   class: GABasedTaskSelector
#   params:
#     interval: 50    # 変更可
#     pop_size: 100
#     generations: 1000
#     elitism_rate: 0.1
#     seed: 123
#     L_max: 5        # 変更可
#     seed: 1234
#     trials: 5

task_selection:
  module: acta.sim.task_selection
  class: ADSBaseSelector
  params:
    alpha_risk: 1.0
    max_rounds: 5

workers_csv: "toy_workers.csv"
tasks_csv:   "toy_tasks.csv"
